config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes, only: [:index, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :get_contentful_object
  
  def index
    @recipes = @contentful.get_all_recipes
    @recipes = RecipeDecorator.decorate_collection(@recipes)
  end
  
  def show
    @recipe = @contentful.get_recipe(params[:id])
    @recipe = RecipeDecorator.decorate(@recipe)
  end  

  private

  def get_contentful_object
    @contentful = ContentfulService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleyTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="page-header">
  <h2>Recipe List</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Image</th>
    </tr>
  </thead>
  <tbody>
    <% if @recipes %>
      <% @recipes.each_with_index do |recipe, index| %>
        <tr>
          <th scope="row"><%= link_to index + 1, recipe_path(recipe.id) %></th>
          <td><%= recipe.title %></td>
          <td><%= image_tag recipe.photo_url, width: 50, height: 50 %></td>
        </tr>
      <% end %>  
    <% end %>    
  </tbody>
</table>

app/views/recipes/show.html.erb
<div class="page-header">
  <h2>Recipe Page</h2>
</div>
<div class="row">
  <div class="col-md-4 mb-3">Title</div>
  <div class="col-md-6 mb-3"><%= @recipe.title %></div>
</div>
<div class="row">
  <div class="col-md-4 mb-3">Image</div>
  <div class="col-md-6 mb-3"><%= image_tag @recipe.photo_url, width: 150, height: 150  %></div>
</div>
<div class="row">
  <div class="col-md-4 mb-3">List Of Tags</div>
  <div class="col-md-6 mb-3"><%= @recipe.tags %></div>
</div>
<div class="row">
  <div class="col-md-4 mb-3">Description</div>
  <div class="col-md-6 mb-3"><%= @recipe.description %></div>
</div>
<div class="row">
  <div class="col-md-4 mb-3">Chef Name</div>
  <div class="col-md-6 mb-3"><%= @recipe.chef_name %></div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Contentful App</a>
    </li>
  </ul>
</nav>